### ISSUE TITLE
🐞🐢[Regex] - email validation does not check for domain after @

### ISSUE THREAD

**Issue by kairo97** [kairo97/gamerPad-frontend#105]

**Comment by maximusDecimalusMeridius** [comment]
/^([a-z0-9_\/.%~!@#\$%\^&\*-=_\+]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/

**Comment by kairo97** [comment]
dropped in a new regex validation -- removed username validation because it is getting checked by required field

**Comment by kairo97** [comment]
--DONE
