### ISSUE TITLE
[MVP] - Add PUT request to ProfileList component

### ISSUE THREAD

**Issue by maximusDecimalusMeridius** [kairo97/gamerPad-frontend#33]

**Comment by maximusDecimalusMeridius** [comment]
- [x] Edit username
- [x] Edit friendcode
- [ ] Edit password
- [x] Update if you're looking for friends
- [ ] Deleting accounts

**Comment by Mayalynn96** [comment]
Maya: Password change needs a new backend route as bcrypt is not supported in React and otherwise the password saves unhashed.

**Comment by Mayalynn96** [comment]
Maya: Need to change backend route for deleting account to include password verification
