### ISSUE TITLE
⭐[SITE] - Get Game list on search

### ISSUE THREAD

**Issue by Mayalynn96** [kairo97/gamerPad-frontend#74]

**Comment by maximusDecimalusMeridius** [comment]
Maya: currently fetching and displaying all games in community - getting id, need to sort out if communities stays (likely will) how to resolve game fetch

**Comment by Mayalynn96** [comment]
Maya: fetch only if at least 3 characters and 2 seconds without typing
Andy: Look for Npm package

**Comment by maximusDecimalusMeridius** [comment]
Needs to implement in the front
